

all: 
	javac *.java

simulation: 
	javac Simulation.java

trafficsystem: 
	javac TrafficSystem.java

car: 
	javac Car.java

carposition: 
	javac CarPosition.java

lane: 
	javac Lane.java

light: 
	javac Light.java

overflowexception: 
	javac OverflowException.java

test: all


clean: 
	$(RM) *.class 
