

all: Simulation.class TrafficSystem.class Car.class CarPosition.class Light.class Lane.class 
	javac *.java

Simulation.class: 
	javac Simulation.java

TrafficSystem.class: 
	javac TrafficSystem.java

Car.class: 
	javac Car.java

CarPosition.class: 
	javac CarPosition.java

Lane.class: 
	javac Lane.java

Light.class: 
	javac Light.java

clean: 
	$(RM) *.class